<?php

//Boutons admin
define("_ADMIN","Page de l'administrateur");
define("_UTILISATEURS","Gestion Utilisateur");
define("_FAQ","Gestion FAQ");
define("_TICKETS","Gestion Tickets");
define("_DECONNEXION","Déconnexion");

//Accueil.php
define("_CONNEXION","Se connecter");
define("_INSCRIPTION","S'inscrire");
define("_RESULTATS","Suivez vos résultats");
define("_PROGRESSION","Découvrez votre progression en temps réel.");
define("_CONNAITREPLUS","Discutez pour en connaître plus");
define("_APTITUDE","Et montrez que vous êtes toujours apte à piloter!");
define("_AVENTURE","Découvrez l'aventure MedMeasure pour connaître vos résultats en temps réel sur votre aptitude de vol");
define("_JOIN","Rejoignez nous aujourd'hui !");
define("_RESEAUX","Connectez-vous également via les réseaux sociaux !");
define("_RESEAUFB","Se connecter avec Facebook");
define("_RESEAUTW","Se connecter avec Twitter");

//admin_faq.php
define("_QUESTIONS","Récapitulatif des questions de la FAQ");
define("_NUMBERQUESTION","Numéro question");

define("_NOUVELLEQUESTION","Création d'une nouvelle question");
define("_FORMNOUVELLEQUESTION","Formulaire de la création d'une question");
define("_INTITULENOUVELLEQUESTION","Intitulé de la question");
define("_REPONSENOUVELLEQUESTION","Réponse de la question");

//admin_ticket.php
//TICKETS
define("_NBTICKETS","Nombre de tickets :");
define("_TICKETSENCOURS","Tickets en cours :");
define("_TICKETSTRAITES","Tickets traités:");
define("_RECAPTICKETS","Récapitulatif des Tickets");
define("_NOMUTILISATEUR","Nom de l'utilisateur");
define("_DATETICKET","Date d'envoi");
define("_INTITULE","Intitulé");
define("_REPONSE","Réponse");
define("_STATUT","Statut");
define("_TERMINE","Terminé");
define("_ENCOURS","En cours");

//admin_user.php
define("_NBUTILISATEURS","Nombre utilisateurs :");
define("_NBPILOTES","Nombre de pilotes :");
define("_NBTESTS","Nombre de tests :");
define("_NBTESTSREUSSIS","Tests réussis :");
define("_DONNEESGENERALES","Récapitulatif des données générales");
define("_NOM","Nom");
define("_PRENOM","Prénom");
define("_DATENAISSANCE","Date de naissance");
define("_SEXE","Sexe");
define("_ADRESSE","Adresse");
define("_VILLE","Ville");
define("_CODEPOSTAL","Code postal");
define("_TELEPHONE","Téléphone");
define("_GESTIONUTILISATEURS","Gestion des utilisateurs");
define("_EMAIL","Email");
define("_TYPE","Type");
define("_VALIDEQ","Validé ?");
define("_ADMINISTRATEUR","Administrateur");
define("_GESTIONNAIRE","Gestionnaire");
define("_PILOTE","Pilote");
define("_VALIDE","Validé");
define("_NONVALIDE","Non Validé");
define("_GESTIONTESTSPARTIELS","Gestion des tests partiels");
define("_GESTIONTESTSCOMPLETS","Gestion des tests complets");
define("_BANNIR", "Êtes-vous sûr de vouloir BANNIR cet utilisateur ?");
define("_DELETEUSER", "Êtes-vous sûr de vouloir supprimer cet utilisateur ?");
define("_DATETEST","Date du test");

//cgu.php
define("_CGU","CGU");
define("_ARTICLE1TITLE","Article 1 : Object");
define("_ARTICLE1","Les présentes CGU ou Conditions Générales d’Utilisation encadrent juridiquement l’utilisation des services du site MedMeasure.

          Constituant le contrat entre la société MedMeasure, l’Utilisateur, l’accès au site doit être précédé de l’acceptation de ces CGU. L’accès à cette plateforme signifie l’acceptation des présentes CGU.");
define("_ARTICLE2TITLE","Article 2 : Mentions légales");
define("_ARTICLE2","L’édition du site MedMeasure est assurée par la société MedMeasure, dont le siège social est localisé au 10 Rue de Vanves, 92130 Issy-les-Moulineaux France Métropolitaine.

          L’hébergeur du site se fait pour l'instant en localhost.");
define("_ARTICLE3TITLE","Article 3 : Accès au site");
define("_ARTICLE31","Le site MedMeasure permet d’accéder gratuitement aux services suivants :");
define("_ARTICLE32","D'effectuer des mesures psychotechniques.");
define("_ARTICLE33","De voir ses résultats.");
define("_ARTICLE34","D'avoir des graphiques sur ses résultats.");
define("_ARTICLE35","Le site est accessible gratuitement depuis n’importe où par tout utilisateur disposant d’un accès à Internet. Tous les frais nécessaires pour l’accès aux services (matériel informatique, connexion Internet…) sont à la charge de l’utilisateur.

            L’accès aux services dédiés aux membres s’effectue à l’aide d’un identifiant et d’un mot de passe.

            Pour des raisons de maintenance ou autres, l’accès au site peut être interrompu ou suspendu par l’éditeur sans préavis ni justification.");
define("_ARTICLE4TITLE","Article 4 : Collecte des données");
define("_ARTICLE41","Pour la création du compte de l’Utilisateur, la collecte des informations au moment de l’inscription sur le site est nécessaire et obligatoire. Conformément à la loi n°78-17 du 6 janvier relative à l’informatique, aux fichiers et aux libertés, la collecte et le traitement d’informations personnelles s’effectuent dans le respect de la vie privée.");
define("_ARTICLE42","De plus, les données seront gardées pendant une durée de 6 mois, puis elles seront supprimées.");
define("_ARTICLE43","Suivant la loi Informatique et Libertés en date du 6 janvier 1978, articles 39 et 40, l’Utilisateur dispose du droit d’accéder, de rectifier, de supprimer et d’opposer ses données personnelles. L’exercice de ce droit s’effectue par :");
define("_ARTICLE44","Le formulaire d'envoi de ticket.");
define("_ARTICLE5TITLE","Article 5 : Propriété intellectuelle");
define("_ARTICLE51","Les marques, logos ainsi que les contenus du site MedMeasure (illustrations graphiques, textes…) sont protégés par le Code de la propriété intellectuelle et par le droit d’auteur.");
define("_ARTICLE52","La reproduction et la copie des contenus par l’Utilisateur requièrent une autorisation préalable du site. Dans ce cas, toute utilisation à des usages commerciaux ou à des fins publicitaires est proscrite.");

//Boutons FAQ.php
define("_ACCUEIL","Accueil");
define("_BOUTONSFAQ","FAQ");

define("_AUTRESQUESTIONS","D'autres questions ?");
define("_CONTACTMAIL","Contactez-nous à l'adresse suivant ");
define("_MAILMEDMEASURE","MedMeasure@gmail.com");
define("_CONTACTTEL"," ou par téléphone au ");
define("_TELMEDMEASURE","01 23 45 67 89");

//Gestionnaire gestionnaire.php
define("_RECHERCHERPILOTE","Rechercher un pilote");
define("_RECHERCHERUSER","Rechercher un utilisateur");
define("_STATISTIQUES","Statistiques -");
define("_TEST","Test");

define("_NORESULT", "Pas de résultat pour");
define("_RESULTATRECHERCHEPILOTE","Voici les pilotes qui correspondent à votre recherche :");
define("_VALIDER","Valider");

define("_SELECTSEXE","Sélectionner le sexe");
define("_HOMME","Homme");
define("_FEMME","Femme");
define("_MESURE", "Sélectionner une mesure");
define("_RYTHMECARDIAQUE","Rythme cardiaque");
define("_PERCEPTIONAUDITIVE","Perception auditive");
define("_STIMULUSVISUEL","Réaction à un stimulus visuel");
define("_TEMPERATUREPEAU","Température de la peau");
define("_RECOTONALITE","Reconnaissance de la tonalité");

define("_CHOIXMESURE", "Choisissez un test pour afficher sa répartition");
define("_REPARTITIONRYTHMECARDIAQUE","Répartition des fréquences cardiaques");
define("_REPARTITIONPERCEPTIONAUDITIVE","Répartition des perceptions auditives");
define("_REPARTITIONSTIMULUSVISUEL","Répartition des réactions à un stimulus visuel");
define("_REPARTITIONTEMPERATUREPEAU","Répartition des températures de la peau");
define("_REPARTITIONRECOTONALITE","Répartition des reconnaissances de la tonalité");

define("_NOTESTPARTIEL","Pas de test partiel malheureusement.");
define("_NOTESTCOMPLET","Pas de test complet malheureusement.<br/>");

//Historique.php
define("_TITREHISTORIQUE","Historique des résultats");

define("_EVOLUTIONSCORE","Evolution des scores");
define("_HISTORIQUE","Historique");
define("_POINTS","Points");
define("_DETAILS","Détails");

//Menu.php
define("_PILOTE2","- Pilote");
define("_DATEDERNIERTESTPARTIEL","Date du dernier test partiel ");
define("_DATEDERNIERTESTCOMPLET","Date du dernier test complet ");
define("_PRETPOURUNTEST","Prêt pour un test ?");
define("_LETSGO", "C'est parti");
define("_MODIFIERPROFIL","Modifier le profil");
define("_ENVOYERTICKET","Envoyer un ticket");
define("_DERNIERRESULTAT","Dernier résultat");

//Modification-profil.php
define("_PROFIL","Profil");
define("_INFOPERSO","Informations personnelles");
define("_ENREGISTRER","Enregistrer");
define("_ANNULER","Annuler");

//PageTest.php
define("_TESTDESUIVI","Test de suivi");
define("_TESTCOMPLET","Test complet");

//resultat-test-partiel.php
define("_RESULTATTESTPARTIEL","Résultat du test partiel");
define("_RESULTATTESTCOMPLET","Résultat du test complet");

//inscription.php
define("_INSCRIPTIONTITLE","Inscription");
define("_INFOCONNEXION","Information de connexion");
define("_MOTDEPASSE","Mot de passe");
define("_ADDRESSEEMAIL","Adresse mail");
define("_CONFIRMEMDP","Confirmer le mot de passe");
define("_LUETACCEPTE","J'ai lu et j'accepte les");
define("_CONDITIONS","conditions générales d'utilisation");

//ticket.php
define("_QUESTIONOBJECT","Quel est l'objet de votre question ?");
define("_DETAILQUESTION","Merci de détailler votre question");
define("_ENVOYER","Envoyer");

//messages dernier résultat
define("_LOW","Il faudrait peut-être consulter un médecin");
define("_MEDIUM","Vous y êtes presque, ne perdez pas espoir");
define("_HIGH","Bravo ! Vous êtes apte à voler");
define("_CLICK","Cliquez ici");
?>
